// !!! DO NOT EDIT THIS FILE
package models

import (
	"database/sql"
	"github.com/mylxsw/eloquent/query"
	"gopkg.in/guregu/null.v3"
	"time"
)

func init() {

	AddProjectGlobalScope("soft_delete", func(builder query.Condition) {
		builder.WhereNull("deleted_at")
	})

}

type Project struct {
	Id          int64
	Name        string
	Description string
	Visibility  int
	UserId      int64
	SortLevel   int
	CatalogId   null.Int

	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt null.Time
}

type projectWrap struct {
	Id          null.Int
	Name        null.String
	Description null.String
	Visibility  null.Int
	UserId      null.Int
	SortLevel   null.Int
	CatalogId   null.Int

	CreatedAt null.Time
	UpdatedAt null.Time
	DeletedAt null.Time
}

func (w projectWrap) ToProject() Project {
	return Project{
		Id:          w.Id.Int64,
		Name:        w.Name.String,
		Description: w.Description.String,
		Visibility:  int(w.Visibility.Int64),
		UserId:      w.UserId.Int64,
		SortLevel:   int(w.SortLevel.Int64),
		CatalogId:   w.CatalogId,

		CreatedAt: w.CreatedAt.Time,
		UpdatedAt: w.UpdatedAt.Time,
		DeletedAt: w.DeletedAt,
	}
}

type ProjectModel struct {
	db        *sql.DB
	tableName string

	excludeGlobalScopes []string
	includeLocalScopes  []string
}

type projectScope struct {
	name  string
	apply func(builder query.Condition)
}

var projectGlobalScopes = make([]projectScope, 0)
var projectLocalScopes = make([]projectScope, 0)

func NewProjectModel(db *sql.DB) *ProjectModel {
	return &ProjectModel{
		db:                  db,
		tableName:           "wz_projects",
		excludeGlobalScopes: make([]string, 0),
		includeLocalScopes:  make([]string, 0),
	}
}

func AddProjectGlobalScope(name string, apply func(builder query.Condition)) {
	projectGlobalScopes = append(projectGlobalScopes, projectScope{name: name, apply: apply})
}

func AddProjectLocalScope(name string, apply func(builder query.Condition)) {
	projectLocalScopes = append(projectLocalScopes, projectScope{name: name, apply: apply})
}

func (m *ProjectModel) applyScope() query.Condition {
	scopeCond := query.ConditionBuilder()
	for _, g := range projectGlobalScopes {
		if m.globalScopeEnabled(g.name) {
			g.apply(scopeCond)
		}
	}

	for _, s := range projectLocalScopes {
		if m.localScopeEnabled(s.name) {
			s.apply(scopeCond)
		}
	}

	return scopeCond
}

func (m *ProjectModel) localScopeEnabled(name string) bool {
	for _, n := range m.includeLocalScopes {
		if name == n {
			return true
		}
	}

	return false
}

func (m *ProjectModel) globalScopeEnabled(name string) bool {
	for _, n := range m.excludeGlobalScopes {
		if name == n {
			return false
		}
	}

	return true
}

func (m *ProjectModel) WithTrashed() *ProjectModel {
	return m.WithoutGlobalScopes("soft_delete")
}

func (m *ProjectModel) clone() *ProjectModel {
	return &ProjectModel{
		db:                  m.db,
		tableName:           m.tableName,
		excludeGlobalScopes: append([]string{}, m.excludeGlobalScopes...),
		includeLocalScopes:  append([]string{}, m.includeLocalScopes...),
	}
}

func (m *ProjectModel) WithoutGlobalScopes(names ...string) *ProjectModel {
	mc := m.clone()
	mc.excludeGlobalScopes = append(mc.excludeGlobalScopes, names...)

	return mc
}

func (m *ProjectModel) WithLocalScopes(names ...string) *ProjectModel {
	mc := m.clone()
	mc.includeLocalScopes = append(mc.includeLocalScopes, names...)

	return mc
}

func (m *ProjectModel) Find(id int64) (Project, error) {
	return m.First(query.Builder().Where("id", "=", id))
}

func (m *ProjectModel) Get(builder query.SQLBuilder) ([]Project, error) {
	builder = builder.Table(m.tableName).Select("id", "created_at", "updated_at", "name", "description", "visibility", "user_id", "sort_level", "catalog_id", "deleted_at")
	sqlStr, params := builder.AppendCondition(m.applyScope()).ResolveQuery()

	rows, err := m.db.Query(sqlStr, params...)
	if err != nil {
		return nil, err
	}

	projects := make([]Project, 0)
	for rows.Next() {
		var projectVar projectWrap
		if err := rows.Scan(&projectVar.Id, &projectVar.CreatedAt, &projectVar.UpdatedAt, &projectVar.Name, &projectVar.Description, &projectVar.Visibility, &projectVar.UserId, &projectVar.SortLevel, &projectVar.CatalogId, &projectVar.DeletedAt); err != nil {
			return nil, err
		}

		projects = append(projects, projectVar.ToProject())
	}

	return projects, nil
}

func (m *ProjectModel) First(builder query.SQLBuilder) (Project, error) {
	res, err := m.Get(builder.Limit(1))
	if err != nil {
		return Project{}, err
	}

	if len(res) == 0 {
		return Project{}, sql.ErrNoRows
	}

	return res[0], nil
}

func (m *ProjectModel) Create(kv query.KV) (int64, error) {
	kv["created_at"] = time.Now()
	kv["updated_at"] = time.Now()

	sqlStr, params := query.Builder().Table(m.tableName).ResolveInsert(kv)

	res, err := m.db.Exec(sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.LastInsertId()
}

func (m *ProjectModel) SaveAll(projects []Project) ([]int64, error) {
	ids := make([]int64, 0)
	for _, project := range projects {
		id, err := m.Save(project)
		if err != nil {
			return ids, err
		}

		ids = append(ids, id)
	}

	return ids, nil
}

func (m *ProjectModel) Save(project Project) (int64, error) {
	return m.Create(query.KV{
		"name":        project.Name,
		"description": project.Description,
		"visibility":  project.Visibility,
		"user_id":     project.UserId,
		"sort_level":  project.SortLevel,
		"catalog_id":  project.CatalogId,
	})
}

func (m *ProjectModel) SaveOrUpdate(project Project) (id int64, updated bool, err error) {
	if project.Id > 0 {
		_, _err := m.UpdateById(project.Id, project)
		return project.Id, true, _err
	}

	_id, _err := m.Save(project)
	return _id, false, _err
}

func (m *ProjectModel) UpdateFields(builder query.SQLBuilder, kv query.KV) (int64, error) {

	kv["updated_at"] = time.Now()

	builder = builder.AppendCondition(m.applyScope())
	sqlStr, params := builder.Table(m.tableName).ResolveUpdate(kv)

	res, err := m.db.Exec(sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()
}

func (m *ProjectModel) Update(builder query.SQLBuilder, project Project) (int64, error) {
	return m.UpdateFields(builder, query.KV{
		"name":        project.Name,
		"description": project.Description,
		"visibility":  project.Visibility,
		"user_id":     project.UserId,
		"sort_level":  project.SortLevel,
		"catalog_id":  project.CatalogId,
	})
}

func (m *ProjectModel) UpdateById(id int64, project Project) (int64, error) {
	return m.Update(query.Builder().Where("id", "=", id), project)
}

func (m *ProjectModel) ForceDelete(builder query.SQLBuilder) (int64, error) {
	m2 := m.WithTrashed()

	sqlStr, params := builder.AppendCondition(m2.applyScope()).Table(m2.tableName).ResolveDelete()

	res, err := m2.db.Exec(sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()
}

func (m *ProjectModel) ForceDeleteById(id int64) (int64, error) {
	return m.ForceDelete(query.Builder().Where("id", "=", id))
}

func (m *ProjectModel) Restore(builder query.SQLBuilder) (int64, error) {
	m2 := m.WithTrashed()
	return m2.UpdateFields(builder, query.KV{
		"deleted_at": nil,
	})
}

func (m *ProjectModel) RestoreById(id int64) (int64, error) {
	return m.Restore(query.Builder().Where("id", "=", id))
}

func (m *ProjectModel) Delete(builder query.SQLBuilder) (int64, error) {

	return m.UpdateFields(builder, query.KV{
		"deleted_at": time.Now(),
	})

}

func (m *ProjectModel) DeleteById(id int64) (int64, error) {
	return m.Delete(query.Builder().Where("id", "=", id))
}
