package models

// !!! DO NOT EDIT THIS FILE

import (
	"context"
	"github.com/iancoleman/strcase"
	"github.com/mylxsw/eloquent"
	"github.com/mylxsw/eloquent/query"
	"gopkg.in/guregu/null.v3"
	"time"
)

func init() {

	// AddUserGlobalScope assign a global scope to a model for soft delete
	AddGlobalScopeForUser("soft_delete", func(builder query.Condition) {
		builder.WhereNull("deleted_at")
	})

}

// User is a User object
type User struct {
	original  *userOriginal
	userModel *UserModel

	Id            int64 `json:"id"`
	Name          string
	Email         string `json:"email"`
	Password      string `json:"password" yaml:"password"`
	RoleId        int64
	EnterpriseId  int64
	RememberToken string `json:"remember_token" yaml:"remember_token"`
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     null.Time
}

// SetModel set model for User
func (inst *User) SetModel(userModel *UserModel) {
	inst.userModel = userModel
}

// userOriginal is an object which stores original User from database
type userOriginal struct {
	Id            int64
	Name          string
	Email         string
	Password      string
	RoleId        int64
	EnterpriseId  int64
	RememberToken string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     null.Time
}

// Staled identify whether the object has been modified
func (inst *User) Staled() bool {
	if inst.original == nil {
		inst.original = &userOriginal{}
	}

	if inst.Id != inst.original.Id {
		return true
	}
	if inst.Name != inst.original.Name {
		return true
	}
	if inst.Email != inst.original.Email {
		return true
	}
	if inst.Password != inst.original.Password {
		return true
	}
	if inst.RoleId != inst.original.RoleId {
		return true
	}
	if inst.EnterpriseId != inst.original.EnterpriseId {
		return true
	}
	if inst.RememberToken != inst.original.RememberToken {
		return true
	}
	if inst.CreatedAt != inst.original.CreatedAt {
		return true
	}
	if inst.UpdatedAt != inst.original.UpdatedAt {
		return true
	}
	if inst.DeletedAt != inst.original.DeletedAt {
		return true
	}

	return false
}

// StaledKV return all fields has been modified
func (inst *User) StaledKV() query.KV {
	kv := make(query.KV, 0)

	if inst.original == nil {
		inst.original = &userOriginal{}
	}

	if inst.Id != inst.original.Id {
		kv["id"] = inst.Id
	}
	if inst.Name != inst.original.Name {
		kv["name"] = inst.Name
	}
	if inst.Email != inst.original.Email {
		kv["email"] = inst.Email
	}
	if inst.Password != inst.original.Password {
		kv["password"] = inst.Password
	}
	if inst.RoleId != inst.original.RoleId {
		kv["role_id"] = inst.RoleId
	}
	if inst.EnterpriseId != inst.original.EnterpriseId {
		kv["enterprise_id"] = inst.EnterpriseId
	}
	if inst.RememberToken != inst.original.RememberToken {
		kv["remember_token"] = inst.RememberToken
	}
	if inst.CreatedAt != inst.original.CreatedAt {
		kv["created_at"] = inst.CreatedAt
	}
	if inst.UpdatedAt != inst.original.UpdatedAt {
		kv["updated_at"] = inst.UpdatedAt
	}
	if inst.DeletedAt != inst.original.DeletedAt {
		kv["deleted_at"] = inst.DeletedAt
	}

	return kv
}

// Save create a new model or update it
func (inst *User) Save() error {
	if inst.userModel == nil {
		return query.ErrModelNotSet
	}

	id, _, err := inst.userModel.SaveOrUpdate(*inst)
	if err != nil {
		return err
	}

	inst.Id = id
	return nil
}

// Delete remove a User
func (inst *User) Delete() error {
	if inst.userModel == nil {
		return query.ErrModelNotSet
	}

	_, err := inst.userModel.DeleteById(inst.Id)
	if err != nil {
		return err
	}

	return nil
}

func (inst *User) Role() *UserBelongsToRoleRel {
	return &UserBelongsToRoleRel{
		source:   inst,
		relModel: NewRoleModel(inst.userModel.GetDB()),
	}
}

type UserBelongsToRoleRel struct {
	source   *User
	relModel *RoleModel
}

func (rel *UserBelongsToRoleRel) Create(target Role) (int64, error) {
	targetId, err := rel.relModel.Save(target)
	if err != nil {
		return 0, err
	}

	target.Id = targetId

	rel.source.RoleId = target.Id
	if err := rel.source.Save(); err != nil {
		return targetId, err
	}

	return targetId, nil
}

func (rel *UserBelongsToRoleRel) Exists(builders ...query.SQLBuilder) (bool, error) {
	builder := query.Builder().Where("id", rel.source.RoleId).Merge(builders...)

	return rel.relModel.Exists(builder)
}

func (rel *UserBelongsToRoleRel) First(builders ...query.SQLBuilder) (Role, error) {
	builder := query.Builder().Where("id", rel.source.RoleId).Limit(1).Merge(builders...)

	return rel.relModel.First(builder)
}

func (rel *UserBelongsToRoleRel) Associate(target Role) error {
	rel.source.RoleId = target.Id
	return rel.source.Save()
}

func (rel *UserBelongsToRoleRel) Dissociate() error {
	rel.source.RoleId = 0
	return rel.source.Save()
}

func (inst *User) Enterprise() *UserBelongsToEnterpriseRel {
	return &UserBelongsToEnterpriseRel{
		source:   inst,
		relModel: NewEnterpriseModel(inst.userModel.GetDB()),
	}
}

type UserBelongsToEnterpriseRel struct {
	source   *User
	relModel *EnterpriseModel
}

func (rel *UserBelongsToEnterpriseRel) Create(target Enterprise) (int64, error) {
	targetId, err := rel.relModel.Save(target)
	if err != nil {
		return 0, err
	}

	target.Id = targetId

	rel.source.EnterpriseId = target.Id
	if err := rel.source.Save(); err != nil {
		return targetId, err
	}

	return targetId, nil
}

func (rel *UserBelongsToEnterpriseRel) Exists(builders ...query.SQLBuilder) (bool, error) {
	builder := query.Builder().Where("id", rel.source.EnterpriseId).Merge(builders...)

	return rel.relModel.Exists(builder)
}

func (rel *UserBelongsToEnterpriseRel) First(builders ...query.SQLBuilder) (Enterprise, error) {
	builder := query.Builder().Where("id", rel.source.EnterpriseId).Limit(1).Merge(builders...)

	return rel.relModel.First(builder)
}

func (rel *UserBelongsToEnterpriseRel) Associate(target Enterprise) error {
	rel.source.EnterpriseId = target.Id
	return rel.source.Save()
}

func (rel *UserBelongsToEnterpriseRel) Dissociate() error {
	rel.source.EnterpriseId = 0
	return rel.source.Save()
}

func (inst *User) UserExt() *UserHasOneUserExtRel {
	return &UserHasOneUserExtRel{
		source:   inst,
		relModel: NewUserExtModel(inst.userModel.GetDB()),
	}
}

type UserHasOneUserExtRel struct {
	source   *User
	relModel *UserExtModel
}

func (rel *UserHasOneUserExtRel) Exists(builders ...query.SQLBuilder) (bool, error) {
	builder := query.Builder().Where("user_id", rel.source.Id).Merge(builders...)

	return rel.relModel.Exists(builder)
}

func (rel *UserHasOneUserExtRel) First(builders ...query.SQLBuilder) (UserExt, error) {
	builder := query.Builder().Where("user_id", rel.source.Id).Limit(1).Merge(builders...)
	return rel.relModel.First(builder)
}

func (rel *UserHasOneUserExtRel) Create(target UserExt) (int64, error) {
	target.UserId = rel.source.Id
	return rel.relModel.Save(target)
}

func (rel *UserHasOneUserExtRel) Associate(target UserExt) error {
	_, err := rel.relModel.UpdateFields(
		query.KV{"user_id": rel.source.Id},
		query.Builder().Where("id", target.Id),
	)
	return err
}

func (rel *UserHasOneUserExtRel) Dissociate() error {
	_, err := rel.relModel.UpdateFields(
		query.KV{"user_id": nil},
		query.Builder().Where("user_id", rel.source.Id),
	)

	return err
}

func (inst *User) Organizations() *UserBelongsToManyOrganizationRel {
	return &UserBelongsToManyOrganizationRel{
		source:     inst,
		pivotTable: "user_organization_ref",
		relModel:   NewOrganizationModel(inst.userModel.GetDB()),
	}
}

type UserBelongsToManyOrganizationRel struct {
	source     *User
	pivotTable string
	relModel   *OrganizationModel
}

func (rel *UserBelongsToManyOrganizationRel) Get(builders ...query.SQLBuilder) ([]Organization, error) {
	res, err := eloquent.DB(rel.relModel.GetDB()).Query(
		query.Builder().Table(rel.pivotTable).Select("organization_id").Where("user_id", rel.source.Id),
		func(row eloquent.Scanner) (interface{}, error) {
			var k interface{}
			if err := row.Scan(&k); err != nil {
				return nil, err
			}

			return k, nil
		},
	)

	if err != nil {
		return nil, err
	}

	resArr, _ := res.ToArray()
	return rel.relModel.Get(query.Builder().Merge(builders...).WhereIn("id", resArr...))
}

func (rel *UserBelongsToManyOrganizationRel) Count(builders ...query.SQLBuilder) (int64, error) {
	res, err := eloquent.DB(rel.relModel.GetDB()).Query(
		query.Builder().Table(rel.pivotTable).Select(query.Raw("COUNT(1) as c")).Where("user_id", rel.source.Id),
		func(row eloquent.Scanner) (interface{}, error) {
			var k int64
			if err := row.Scan(&k); err != nil {
				return nil, err
			}

			return k, nil
		},
	)

	if err != nil {
		return 0, err
	}

	return res.Index(0).(int64), nil
}

func (rel *UserBelongsToManyOrganizationRel) Exists(builders ...query.SQLBuilder) (bool, error) {
	c, err := rel.Count(builders...)
	if err != nil {
		return false, err
	}

	return c > 0, nil
}

func (rel *UserBelongsToManyOrganizationRel) Attach(target Organization) error {
	_, err := eloquent.DB(rel.relModel.GetDB()).Insert(rel.pivotTable, query.KV{
		"organization_id": target.Id,
		"user_id":         rel.source.Id,
	})

	return err
}

func (rel *UserBelongsToManyOrganizationRel) Detach(target Organization) error {
	_, err := eloquent.DB(rel.relModel.GetDB()).
		Delete(eloquent.Build(rel.pivotTable).
			Where("organization_id", target.Id).
			Where("user_id", rel.source.Id))

	return err
}

func (rel *UserBelongsToManyOrganizationRel) DetachAll() error {
	_, err := eloquent.DB(rel.relModel.GetDB()).
		Delete(eloquent.Build(rel.pivotTable).
			Where("user_id", rel.source.Id))
	return err
}

func (rel *UserBelongsToManyOrganizationRel) Create(target Organization, builders ...query.SQLBuilder) (int64, error) {
	targetId, err := rel.relModel.Save(target)
	if err != nil {
		return 0, err
	}

	target.Id = targetId

	err = rel.Attach(target)

	return targetId, err
}

type userScope struct {
	name  string
	apply func(builder query.Condition)
}

var userGlobalScopes = make([]userScope, 0)
var userLocalScopes = make([]userScope, 0)

// AddGlobalScopeForUser assign a global scope to a model
func AddGlobalScopeForUser(name string, apply func(builder query.Condition)) {
	userGlobalScopes = append(userGlobalScopes, userScope{name: name, apply: apply})
}

// AddLocalScopeForUser assign a local scope to a model
func AddLocalScopeForUser(name string, apply func(builder query.Condition)) {
	userLocalScopes = append(userLocalScopes, userScope{name: name, apply: apply})
}

func (m *UserModel) applyScope() query.Condition {
	scopeCond := query.ConditionBuilder()
	for _, g := range userGlobalScopes {
		if m.globalScopeEnabled(g.name) {
			g.apply(scopeCond)
		}
	}

	for _, s := range userLocalScopes {
		if m.localScopeEnabled(s.name) {
			s.apply(scopeCond)
		}
	}

	return scopeCond
}

func (m *UserModel) localScopeEnabled(name string) bool {
	for _, n := range m.includeLocalScopes {
		if name == n {
			return true
		}
	}

	return false
}

func (m *UserModel) globalScopeEnabled(name string) bool {
	for _, n := range m.excludeGlobalScopes {
		if name == n {
			return false
		}
	}

	return true
}

type userWrap struct {
	Id            null.Int
	Name          null.String
	Email         null.String
	Password      null.String
	RoleId        null.Int
	EnterpriseId  null.Int
	RememberToken null.String
	CreatedAt     null.Time
	UpdatedAt     null.Time
	DeletedAt     null.Time
}

func (w userWrap) ToUser() User {
	return User{
		original: &userOriginal{
			Id:            w.Id.Int64,
			Name:          w.Name.String,
			Email:         w.Email.String,
			Password:      w.Password.String,
			RoleId:        w.RoleId.Int64,
			EnterpriseId:  w.EnterpriseId.Int64,
			RememberToken: w.RememberToken.String,
			CreatedAt:     w.CreatedAt.Time,
			UpdatedAt:     w.UpdatedAt.Time,
			DeletedAt:     w.DeletedAt,
		},

		Id:            w.Id.Int64,
		Name:          w.Name.String,
		Email:         w.Email.String,
		Password:      w.Password.String,
		RoleId:        w.RoleId.Int64,
		EnterpriseId:  w.EnterpriseId.Int64,
		RememberToken: w.RememberToken.String,
		CreatedAt:     w.CreatedAt.Time,
		UpdatedAt:     w.UpdatedAt.Time,
		DeletedAt:     w.DeletedAt,
	}
}

// UserModel is a model which encapsulates the operations of the object
type UserModel struct {
	db        *query.DatabaseWrap
	tableName string

	excludeGlobalScopes []string
	includeLocalScopes  []string

	query query.SQLBuilder
}

var userTableName = "wz_user"

func SetUserTable(tableName string) {
	userTableName = tableName
}

// NewUserModel create a UserModel
func NewUserModel(db query.Database) *UserModel {
	return &UserModel{
		db:                  query.NewDatabaseWrap(db),
		tableName:           userTableName,
		excludeGlobalScopes: make([]string, 0),
		includeLocalScopes:  make([]string, 0),
		query:               query.Builder(),
	}
}

// GetDB return database instance
func (m *UserModel) GetDB() query.Database {
	return m.db.GetDB()
}

// WithTrashed force soft deleted models to appear in a result set
func (m *UserModel) WithTrashed() *UserModel {
	return m.WithoutGlobalScopes("soft_delete")
}

func (m *UserModel) clone() *UserModel {
	return &UserModel{
		db:                  m.db,
		tableName:           m.tableName,
		excludeGlobalScopes: append([]string{}, m.excludeGlobalScopes...),
		includeLocalScopes:  append([]string{}, m.includeLocalScopes...),
		query:               m.query,
	}
}

// WithoutGlobalScopes remove a global scope for given query
func (m *UserModel) WithoutGlobalScopes(names ...string) *UserModel {
	mc := m.clone()
	mc.excludeGlobalScopes = append(mc.excludeGlobalScopes, names...)

	return mc
}

// WithLocalScopes add a local scope for given query
func (m *UserModel) WithLocalScopes(names ...string) *UserModel {
	mc := m.clone()
	mc.includeLocalScopes = append(mc.includeLocalScopes, names...)

	return mc
}

// Query add query builder to model
func (m *UserModel) Query(builder query.SQLBuilder) *UserModel {
	mm := m.clone()
	mm.query = mm.query.Merge(builder)

	return mm
}

// Find retrieve a model by its primary key
func (m *UserModel) Find(id int64) (User, error) {
	return m.First(m.query.Where("id", "=", id))
}

// Exists return whether the records exists for a given query
func (m *UserModel) Exists(builders ...query.SQLBuilder) (bool, error) {
	count, err := m.Count(builders...)
	return count > 0, err
}

// Count return model count for a given query
func (m *UserModel) Count(builders ...query.SQLBuilder) (int64, error) {
	sqlStr, params := m.query.
		Merge(builders...).
		Table(m.tableName).
		AppendCondition(m.applyScope()).
		ResolveCount()

	rows, err := m.db.QueryContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	defer rows.Close()

	rows.Next()
	var res int64
	if err := rows.Scan(&res); err != nil {
		return 0, err
	}

	return res, nil
}

func (m *UserModel) Paginate(page int64, perPage int64, builders ...query.SQLBuilder) ([]User, query.PaginateMeta, error) {
	if page <= 0 {
		page = 1
	}

	if perPage <= 0 {
		perPage = 15
	}

	meta := query.PaginateMeta{
		PerPage: perPage,
		Page:    page,
	}

	count, err := m.Count(builders...)
	if err != nil {
		return nil, meta, err
	}

	meta.Total = count
	meta.LastPage = count / perPage
	if count%perPage != 0 {
		meta.LastPage += 1
	}

	res, err := m.Get(append([]query.SQLBuilder{query.Builder().Limit(perPage).Offset((page - 1) * perPage)}, builders...)...)
	if err != nil {
		return res, meta, err
	}

	return res, meta, nil
}

// Get retrieve all results for given query
func (m *UserModel) Get(builders ...query.SQLBuilder) ([]User, error) {
	b := m.query.Merge(builders...).Table(m.tableName).AppendCondition(m.applyScope())
	if len(b.GetFields()) == 0 {
		b = b.Select(
			"id",
			"name",
			"email",
			"password",
			"role_id",
			"enterprise_id",
			"remember_token",
			"created_at",
			"updated_at",
			"deleted_at",
		)
	}

	fields := b.GetFields()
	selectFields := make([]query.Expr, 0)

	for _, f := range fields {
		switch strcase.ToSnake(f.Value) {

		case "id":
			selectFields = append(selectFields, f)
		case "name":
			selectFields = append(selectFields, f)
		case "email":
			selectFields = append(selectFields, f)
		case "password":
			selectFields = append(selectFields, f)
		case "role_id":
			selectFields = append(selectFields, f)
		case "enterprise_id":
			selectFields = append(selectFields, f)
		case "remember_token":
			selectFields = append(selectFields, f)
		case "created_at":
			selectFields = append(selectFields, f)
		case "updated_at":
			selectFields = append(selectFields, f)
		case "deleted_at":
			selectFields = append(selectFields, f)
		}
	}

	var createScanVar = func(fields []query.Expr) (*userWrap, []interface{}) {
		var userVar userWrap
		scanFields := make([]interface{}, 0)

		for _, f := range fields {
			switch strcase.ToSnake(f.Value) {

			case "id":
				scanFields = append(scanFields, &userVar.Id)
			case "name":
				scanFields = append(scanFields, &userVar.Name)
			case "email":
				scanFields = append(scanFields, &userVar.Email)
			case "password":
				scanFields = append(scanFields, &userVar.Password)
			case "role_id":
				scanFields = append(scanFields, &userVar.RoleId)
			case "enterprise_id":
				scanFields = append(scanFields, &userVar.EnterpriseId)
			case "remember_token":
				scanFields = append(scanFields, &userVar.RememberToken)
			case "created_at":
				scanFields = append(scanFields, &userVar.CreatedAt)
			case "updated_at":
				scanFields = append(scanFields, &userVar.UpdatedAt)
			case "deleted_at":
				scanFields = append(scanFields, &userVar.DeletedAt)
			}
		}

		return &userVar, scanFields
	}

	sqlStr, params := b.Fields(selectFields...).ResolveQuery()

	rows, err := m.db.QueryContext(context.Background(), sqlStr, params...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	users := make([]User, 0)
	for rows.Next() {
		userVar, scanFields := createScanVar(fields)
		if err := rows.Scan(scanFields...); err != nil {
			return nil, err
		}

		userReal := userVar.ToUser()
		userReal.SetModel(m)
		users = append(users, userReal)
	}

	return users, nil
}

// First return first result for given query
func (m *UserModel) First(builders ...query.SQLBuilder) (User, error) {
	res, err := m.Get(append(builders, query.Builder().Limit(1))...)
	if err != nil {
		return User{}, err
	}

	if len(res) == 0 {
		return User{}, query.ErrNoResult
	}

	return res[0], nil
}

// Create save a new User to database
func (m *UserModel) Create(kv query.KV) (int64, error) {

	if _, ok := kv["created_at"]; !ok {
		kv["created_at"] = time.Now()
	}

	if _, ok := kv["updated_at"]; !ok {
		kv["updated_at"] = time.Now()
	}

	sqlStr, params := m.query.Table(m.tableName).ResolveInsert(kv)

	res, err := m.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.LastInsertId()
}

// SaveAll save all Users to database
func (m *UserModel) SaveAll(users []User) ([]int64, error) {
	ids := make([]int64, 0)
	for _, user := range users {
		id, err := m.Save(user)
		if err != nil {
			return ids, err
		}

		ids = append(ids, id)
	}

	return ids, nil
}

// Save save a User to database
func (m *UserModel) Save(user User) (int64, error) {
	return m.Create(user.StaledKV())
}

// SaveOrUpdate save a new User or update it when it has a id > 0
func (m *UserModel) SaveOrUpdate(user User) (id int64, updated bool, err error) {
	if user.Id > 0 {
		_, _err := m.UpdateById(user.Id, user)
		return user.Id, true, _err
	}

	_id, _err := m.Save(user)
	return _id, false, _err
}

// UpdateFields update kv for a given query
func (m *UserModel) UpdateFields(kv query.KV, builders ...query.SQLBuilder) (int64, error) {
	if len(kv) == 0 {
		return 0, nil
	}

	kv["updated_at"] = time.Now()

	sqlStr, params := m.query.Merge(builders...).AppendCondition(m.applyScope()).
		Table(m.tableName).
		ResolveUpdate(kv)

	res, err := m.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()
}

// Update update a model for given query
func (m *UserModel) Update(user User) (int64, error) {
	return m.UpdateFields(user.StaledKV())
}

// UpdateById update a model by id
func (m *UserModel) UpdateById(id int64, user User) (int64, error) {
	return m.Query(query.Builder().Where("id", "=", id)).Update(user)
}

// ForceDelete permanently remove a soft deleted model from the database
func (m *UserModel) ForceDelete(builders ...query.SQLBuilder) (int64, error) {
	m2 := m.WithTrashed()

	sqlStr, params := m2.query.Merge(builders...).AppendCondition(m2.applyScope()).Table(m2.tableName).ResolveDelete()

	res, err := m2.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()
}

// ForceDeleteById permanently remove a soft deleted model from the database by id
func (m *UserModel) ForceDeleteById(id int64) (int64, error) {
	return m.Query(query.Builder().Where("id", "=", id)).ForceDelete()
}

// Restore restore a soft deleted model into an active state
func (m *UserModel) Restore(builders ...query.SQLBuilder) (int64, error) {
	m2 := m.WithTrashed()
	return m2.UpdateFields(query.KV{
		"deleted_at": nil,
	}, builders...)
}

// RestoreById restore a soft deleted model into an active state by id
func (m *UserModel) RestoreById(id int64) (int64, error) {
	return m.Query(query.Builder().Where("id", "=", id)).Restore()
}

// Delete remove a model
func (m *UserModel) Delete(builders ...query.SQLBuilder) (int64, error) {

	return m.UpdateFields(query.KV{
		"deleted_at": time.Now(),
	}, builders...)

}

// DeleteById remove a model by id
func (m *UserModel) DeleteById(id int64) (int64, error) {
	return m.Query(query.Builder().Where("id", "=", id)).Delete()
}

// UserExt is a UserExt object
type UserExt struct {
	original     *userExtOriginal
	userExtModel *UserExtModel

	Address   string
	Qq        string
	Wechat    string
	UserId    int64
	Id        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

// SetModel set model for UserExt
func (inst *UserExt) SetModel(userExtModel *UserExtModel) {
	inst.userExtModel = userExtModel
}

// userExtOriginal is an object which stores original UserExt from database
type userExtOriginal struct {
	Address   string
	Qq        string
	Wechat    string
	UserId    int64
	Id        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Staled identify whether the object has been modified
func (inst *UserExt) Staled() bool {
	if inst.original == nil {
		inst.original = &userExtOriginal{}
	}

	if inst.Address != inst.original.Address {
		return true
	}
	if inst.Qq != inst.original.Qq {
		return true
	}
	if inst.Wechat != inst.original.Wechat {
		return true
	}
	if inst.UserId != inst.original.UserId {
		return true
	}
	if inst.Id != inst.original.Id {
		return true
	}
	if inst.CreatedAt != inst.original.CreatedAt {
		return true
	}
	if inst.UpdatedAt != inst.original.UpdatedAt {
		return true
	}

	return false
}

// StaledKV return all fields has been modified
func (inst *UserExt) StaledKV() query.KV {
	kv := make(query.KV, 0)

	if inst.original == nil {
		inst.original = &userExtOriginal{}
	}

	if inst.Address != inst.original.Address {
		kv["address"] = inst.Address
	}
	if inst.Qq != inst.original.Qq {
		kv["qq"] = inst.Qq
	}
	if inst.Wechat != inst.original.Wechat {
		kv["wechat"] = inst.Wechat
	}
	if inst.UserId != inst.original.UserId {
		kv["user_id"] = inst.UserId
	}
	if inst.Id != inst.original.Id {
		kv["id"] = inst.Id
	}
	if inst.CreatedAt != inst.original.CreatedAt {
		kv["created_at"] = inst.CreatedAt
	}
	if inst.UpdatedAt != inst.original.UpdatedAt {
		kv["updated_at"] = inst.UpdatedAt
	}

	return kv
}

// Save create a new model or update it
func (inst *UserExt) Save() error {
	if inst.userExtModel == nil {
		return query.ErrModelNotSet
	}

	id, _, err := inst.userExtModel.SaveOrUpdate(*inst)
	if err != nil {
		return err
	}

	inst.Id = id
	return nil
}

// Delete remove a UserExt
func (inst *UserExt) Delete() error {
	if inst.userExtModel == nil {
		return query.ErrModelNotSet
	}

	_, err := inst.userExtModel.DeleteById(inst.Id)
	if err != nil {
		return err
	}

	return nil
}

func (inst *UserExt) User() *UserExtBelongsToUserRel {
	return &UserExtBelongsToUserRel{
		source:   inst,
		relModel: NewUserModel(inst.userExtModel.GetDB()),
	}
}

type UserExtBelongsToUserRel struct {
	source   *UserExt
	relModel *UserModel
}

func (rel *UserExtBelongsToUserRel) Create(target User) (int64, error) {
	targetId, err := rel.relModel.Save(target)
	if err != nil {
		return 0, err
	}

	target.Id = targetId

	rel.source.UserId = target.Id
	if err := rel.source.Save(); err != nil {
		return targetId, err
	}

	return targetId, nil
}

func (rel *UserExtBelongsToUserRel) Exists(builders ...query.SQLBuilder) (bool, error) {
	builder := query.Builder().Where("id", rel.source.UserId).Merge(builders...)

	return rel.relModel.Exists(builder)
}

func (rel *UserExtBelongsToUserRel) First(builders ...query.SQLBuilder) (User, error) {
	builder := query.Builder().Where("id", rel.source.UserId).Limit(1).Merge(builders...)

	return rel.relModel.First(builder)
}

func (rel *UserExtBelongsToUserRel) Associate(target User) error {
	rel.source.UserId = target.Id
	return rel.source.Save()
}

func (rel *UserExtBelongsToUserRel) Dissociate() error {
	rel.source.UserId = 0
	return rel.source.Save()
}

type userExtScope struct {
	name  string
	apply func(builder query.Condition)
}

var userExtGlobalScopes = make([]userExtScope, 0)
var userExtLocalScopes = make([]userExtScope, 0)

// AddGlobalScopeForUserExt assign a global scope to a model
func AddGlobalScopeForUserExt(name string, apply func(builder query.Condition)) {
	userExtGlobalScopes = append(userExtGlobalScopes, userExtScope{name: name, apply: apply})
}

// AddLocalScopeForUserExt assign a local scope to a model
func AddLocalScopeForUserExt(name string, apply func(builder query.Condition)) {
	userExtLocalScopes = append(userExtLocalScopes, userExtScope{name: name, apply: apply})
}

func (m *UserExtModel) applyScope() query.Condition {
	scopeCond := query.ConditionBuilder()
	for _, g := range userExtGlobalScopes {
		if m.globalScopeEnabled(g.name) {
			g.apply(scopeCond)
		}
	}

	for _, s := range userExtLocalScopes {
		if m.localScopeEnabled(s.name) {
			s.apply(scopeCond)
		}
	}

	return scopeCond
}

func (m *UserExtModel) localScopeEnabled(name string) bool {
	for _, n := range m.includeLocalScopes {
		if name == n {
			return true
		}
	}

	return false
}

func (m *UserExtModel) globalScopeEnabled(name string) bool {
	for _, n := range m.excludeGlobalScopes {
		if name == n {
			return false
		}
	}

	return true
}

type userExtWrap struct {
	Address   null.String
	Qq        null.String
	Wechat    null.String
	UserId    null.Int
	Id        null.Int
	CreatedAt null.Time
	UpdatedAt null.Time
}

func (w userExtWrap) ToUserExt() UserExt {
	return UserExt{
		original: &userExtOriginal{
			Address:   w.Address.String,
			Qq:        w.Qq.String,
			Wechat:    w.Wechat.String,
			UserId:    w.UserId.Int64,
			Id:        w.Id.Int64,
			CreatedAt: w.CreatedAt.Time,
			UpdatedAt: w.UpdatedAt.Time,
		},

		Address:   w.Address.String,
		Qq:        w.Qq.String,
		Wechat:    w.Wechat.String,
		UserId:    w.UserId.Int64,
		Id:        w.Id.Int64,
		CreatedAt: w.CreatedAt.Time,
		UpdatedAt: w.UpdatedAt.Time,
	}
}

// UserExtModel is a model which encapsulates the operations of the object
type UserExtModel struct {
	db        *query.DatabaseWrap
	tableName string

	excludeGlobalScopes []string
	includeLocalScopes  []string

	query query.SQLBuilder
}

var userExtTableName = "wz_userext"

func SetUserExtTable(tableName string) {
	userExtTableName = tableName
}

// NewUserExtModel create a UserExtModel
func NewUserExtModel(db query.Database) *UserExtModel {
	return &UserExtModel{
		db:                  query.NewDatabaseWrap(db),
		tableName:           userExtTableName,
		excludeGlobalScopes: make([]string, 0),
		includeLocalScopes:  make([]string, 0),
		query:               query.Builder(),
	}
}

// GetDB return database instance
func (m *UserExtModel) GetDB() query.Database {
	return m.db.GetDB()
}

func (m *UserExtModel) clone() *UserExtModel {
	return &UserExtModel{
		db:                  m.db,
		tableName:           m.tableName,
		excludeGlobalScopes: append([]string{}, m.excludeGlobalScopes...),
		includeLocalScopes:  append([]string{}, m.includeLocalScopes...),
		query:               m.query,
	}
}

// WithoutGlobalScopes remove a global scope for given query
func (m *UserExtModel) WithoutGlobalScopes(names ...string) *UserExtModel {
	mc := m.clone()
	mc.excludeGlobalScopes = append(mc.excludeGlobalScopes, names...)

	return mc
}

// WithLocalScopes add a local scope for given query
func (m *UserExtModel) WithLocalScopes(names ...string) *UserExtModel {
	mc := m.clone()
	mc.includeLocalScopes = append(mc.includeLocalScopes, names...)

	return mc
}

// Query add query builder to model
func (m *UserExtModel) Query(builder query.SQLBuilder) *UserExtModel {
	mm := m.clone()
	mm.query = mm.query.Merge(builder)

	return mm
}

// Find retrieve a model by its primary key
func (m *UserExtModel) Find(id int64) (UserExt, error) {
	return m.First(m.query.Where("id", "=", id))
}

// Exists return whether the records exists for a given query
func (m *UserExtModel) Exists(builders ...query.SQLBuilder) (bool, error) {
	count, err := m.Count(builders...)
	return count > 0, err
}

// Count return model count for a given query
func (m *UserExtModel) Count(builders ...query.SQLBuilder) (int64, error) {
	sqlStr, params := m.query.
		Merge(builders...).
		Table(m.tableName).
		AppendCondition(m.applyScope()).
		ResolveCount()

	rows, err := m.db.QueryContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	defer rows.Close()

	rows.Next()
	var res int64
	if err := rows.Scan(&res); err != nil {
		return 0, err
	}

	return res, nil
}

func (m *UserExtModel) Paginate(page int64, perPage int64, builders ...query.SQLBuilder) ([]UserExt, query.PaginateMeta, error) {
	if page <= 0 {
		page = 1
	}

	if perPage <= 0 {
		perPage = 15
	}

	meta := query.PaginateMeta{
		PerPage: perPage,
		Page:    page,
	}

	count, err := m.Count(builders...)
	if err != nil {
		return nil, meta, err
	}

	meta.Total = count
	meta.LastPage = count / perPage
	if count%perPage != 0 {
		meta.LastPage += 1
	}

	res, err := m.Get(append([]query.SQLBuilder{query.Builder().Limit(perPage).Offset((page - 1) * perPage)}, builders...)...)
	if err != nil {
		return res, meta, err
	}

	return res, meta, nil
}

// Get retrieve all results for given query
func (m *UserExtModel) Get(builders ...query.SQLBuilder) ([]UserExt, error) {
	b := m.query.Merge(builders...).Table(m.tableName).AppendCondition(m.applyScope())
	if len(b.GetFields()) == 0 {
		b = b.Select(
			"address",
			"qq",
			"wechat",
			"user_id",
			"id",
			"created_at",
			"updated_at",
		)
	}

	fields := b.GetFields()
	selectFields := make([]query.Expr, 0)

	for _, f := range fields {
		switch strcase.ToSnake(f.Value) {

		case "address":
			selectFields = append(selectFields, f)
		case "qq":
			selectFields = append(selectFields, f)
		case "wechat":
			selectFields = append(selectFields, f)
		case "user_id":
			selectFields = append(selectFields, f)
		case "id":
			selectFields = append(selectFields, f)
		case "created_at":
			selectFields = append(selectFields, f)
		case "updated_at":
			selectFields = append(selectFields, f)
		}
	}

	var createScanVar = func(fields []query.Expr) (*userExtWrap, []interface{}) {
		var userExtVar userExtWrap
		scanFields := make([]interface{}, 0)

		for _, f := range fields {
			switch strcase.ToSnake(f.Value) {

			case "address":
				scanFields = append(scanFields, &userExtVar.Address)
			case "qq":
				scanFields = append(scanFields, &userExtVar.Qq)
			case "wechat":
				scanFields = append(scanFields, &userExtVar.Wechat)
			case "user_id":
				scanFields = append(scanFields, &userExtVar.UserId)
			case "id":
				scanFields = append(scanFields, &userExtVar.Id)
			case "created_at":
				scanFields = append(scanFields, &userExtVar.CreatedAt)
			case "updated_at":
				scanFields = append(scanFields, &userExtVar.UpdatedAt)
			}
		}

		return &userExtVar, scanFields
	}

	sqlStr, params := b.Fields(selectFields...).ResolveQuery()

	rows, err := m.db.QueryContext(context.Background(), sqlStr, params...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	userExts := make([]UserExt, 0)
	for rows.Next() {
		userExtVar, scanFields := createScanVar(fields)
		if err := rows.Scan(scanFields...); err != nil {
			return nil, err
		}

		userExtReal := userExtVar.ToUserExt()
		userExtReal.SetModel(m)
		userExts = append(userExts, userExtReal)
	}

	return userExts, nil
}

// First return first result for given query
func (m *UserExtModel) First(builders ...query.SQLBuilder) (UserExt, error) {
	res, err := m.Get(append(builders, query.Builder().Limit(1))...)
	if err != nil {
		return UserExt{}, err
	}

	if len(res) == 0 {
		return UserExt{}, query.ErrNoResult
	}

	return res[0], nil
}

// Create save a new UserExt to database
func (m *UserExtModel) Create(kv query.KV) (int64, error) {

	if _, ok := kv["created_at"]; !ok {
		kv["created_at"] = time.Now()
	}

	if _, ok := kv["updated_at"]; !ok {
		kv["updated_at"] = time.Now()
	}

	sqlStr, params := m.query.Table(m.tableName).ResolveInsert(kv)

	res, err := m.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.LastInsertId()
}

// SaveAll save all UserExts to database
func (m *UserExtModel) SaveAll(userExts []UserExt) ([]int64, error) {
	ids := make([]int64, 0)
	for _, userExt := range userExts {
		id, err := m.Save(userExt)
		if err != nil {
			return ids, err
		}

		ids = append(ids, id)
	}

	return ids, nil
}

// Save save a UserExt to database
func (m *UserExtModel) Save(userExt UserExt) (int64, error) {
	return m.Create(userExt.StaledKV())
}

// SaveOrUpdate save a new UserExt or update it when it has a id > 0
func (m *UserExtModel) SaveOrUpdate(userExt UserExt) (id int64, updated bool, err error) {
	if userExt.Id > 0 {
		_, _err := m.UpdateById(userExt.Id, userExt)
		return userExt.Id, true, _err
	}

	_id, _err := m.Save(userExt)
	return _id, false, _err
}

// UpdateFields update kv for a given query
func (m *UserExtModel) UpdateFields(kv query.KV, builders ...query.SQLBuilder) (int64, error) {
	if len(kv) == 0 {
		return 0, nil
	}

	kv["updated_at"] = time.Now()

	sqlStr, params := m.query.Merge(builders...).AppendCondition(m.applyScope()).
		Table(m.tableName).
		ResolveUpdate(kv)

	res, err := m.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()
}

// Update update a model for given query
func (m *UserExtModel) Update(userExt UserExt) (int64, error) {
	return m.UpdateFields(userExt.StaledKV())
}

// UpdateById update a model by id
func (m *UserExtModel) UpdateById(id int64, userExt UserExt) (int64, error) {
	return m.Query(query.Builder().Where("id", "=", id)).Update(userExt)
}

// Delete remove a model
func (m *UserExtModel) Delete(builders ...query.SQLBuilder) (int64, error) {

	sqlStr, params := m.query.Merge(builders...).AppendCondition(m.applyScope()).Table(m.tableName).ResolveDelete()

	res, err := m.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()

}

// DeleteById remove a model by id
func (m *UserExtModel) DeleteById(id int64) (int64, error) {
	return m.Query(query.Builder().Where("id", "=", id)).Delete()
}

// PasswordReset is a PasswordReset object
type PasswordReset struct {
	original           *passwordResetOriginal
	passwordResetModel *PasswordResetModel

	Email     string
	Token     string
	Id        int64
	CreatedAt time.Time
}

// SetModel set model for PasswordReset
func (inst *PasswordReset) SetModel(passwordResetModel *PasswordResetModel) {
	inst.passwordResetModel = passwordResetModel
}

// passwordResetOriginal is an object which stores original PasswordReset from database
type passwordResetOriginal struct {
	Email     string
	Token     string
	Id        int64
	CreatedAt time.Time
}

// Staled identify whether the object has been modified
func (inst *PasswordReset) Staled() bool {
	if inst.original == nil {
		inst.original = &passwordResetOriginal{}
	}

	if inst.Email != inst.original.Email {
		return true
	}
	if inst.Token != inst.original.Token {
		return true
	}
	if inst.Id != inst.original.Id {
		return true
	}
	if inst.CreatedAt != inst.original.CreatedAt {
		return true
	}

	return false
}

// StaledKV return all fields has been modified
func (inst *PasswordReset) StaledKV() query.KV {
	kv := make(query.KV, 0)

	if inst.original == nil {
		inst.original = &passwordResetOriginal{}
	}

	if inst.Email != inst.original.Email {
		kv["email"] = inst.Email
	}
	if inst.Token != inst.original.Token {
		kv["token"] = inst.Token
	}
	if inst.Id != inst.original.Id {
		kv["id"] = inst.Id
	}
	if inst.CreatedAt != inst.original.CreatedAt {
		kv["created_at"] = inst.CreatedAt
	}

	return kv
}

// Save create a new model or update it
func (inst *PasswordReset) Save() error {
	if inst.passwordResetModel == nil {
		return query.ErrModelNotSet
	}

	id, _, err := inst.passwordResetModel.SaveOrUpdate(*inst)
	if err != nil {
		return err
	}

	inst.Id = id
	return nil
}

// Delete remove a PasswordReset
func (inst *PasswordReset) Delete() error {
	if inst.passwordResetModel == nil {
		return query.ErrModelNotSet
	}

	_, err := inst.passwordResetModel.DeleteById(inst.Id)
	if err != nil {
		return err
	}

	return nil
}

type passwordResetScope struct {
	name  string
	apply func(builder query.Condition)
}

var passwordResetGlobalScopes = make([]passwordResetScope, 0)
var passwordResetLocalScopes = make([]passwordResetScope, 0)

// AddGlobalScopeForPasswordReset assign a global scope to a model
func AddGlobalScopeForPasswordReset(name string, apply func(builder query.Condition)) {
	passwordResetGlobalScopes = append(passwordResetGlobalScopes, passwordResetScope{name: name, apply: apply})
}

// AddLocalScopeForPasswordReset assign a local scope to a model
func AddLocalScopeForPasswordReset(name string, apply func(builder query.Condition)) {
	passwordResetLocalScopes = append(passwordResetLocalScopes, passwordResetScope{name: name, apply: apply})
}

func (m *PasswordResetModel) applyScope() query.Condition {
	scopeCond := query.ConditionBuilder()
	for _, g := range passwordResetGlobalScopes {
		if m.globalScopeEnabled(g.name) {
			g.apply(scopeCond)
		}
	}

	for _, s := range passwordResetLocalScopes {
		if m.localScopeEnabled(s.name) {
			s.apply(scopeCond)
		}
	}

	return scopeCond
}

func (m *PasswordResetModel) localScopeEnabled(name string) bool {
	for _, n := range m.includeLocalScopes {
		if name == n {
			return true
		}
	}

	return false
}

func (m *PasswordResetModel) globalScopeEnabled(name string) bool {
	for _, n := range m.excludeGlobalScopes {
		if name == n {
			return false
		}
	}

	return true
}

type passwordResetWrap struct {
	Email     null.String
	Token     null.String
	Id        null.Int
	CreatedAt null.Time
}

func (w passwordResetWrap) ToPasswordReset() PasswordReset {
	return PasswordReset{
		original: &passwordResetOriginal{
			Email:     w.Email.String,
			Token:     w.Token.String,
			Id:        w.Id.Int64,
			CreatedAt: w.CreatedAt.Time,
		},

		Email:     w.Email.String,
		Token:     w.Token.String,
		Id:        w.Id.Int64,
		CreatedAt: w.CreatedAt.Time,
	}
}

// PasswordResetModel is a model which encapsulates the operations of the object
type PasswordResetModel struct {
	db        *query.DatabaseWrap
	tableName string

	excludeGlobalScopes []string
	includeLocalScopes  []string

	query query.SQLBuilder
}

var passwordResetTableName = "wz_passwordreset"

func SetPasswordResetTable(tableName string) {
	passwordResetTableName = tableName
}

// NewPasswordResetModel create a PasswordResetModel
func NewPasswordResetModel(db query.Database) *PasswordResetModel {
	return &PasswordResetModel{
		db:                  query.NewDatabaseWrap(db),
		tableName:           passwordResetTableName,
		excludeGlobalScopes: make([]string, 0),
		includeLocalScopes:  make([]string, 0),
		query:               query.Builder(),
	}
}

// GetDB return database instance
func (m *PasswordResetModel) GetDB() query.Database {
	return m.db.GetDB()
}

func (m *PasswordResetModel) clone() *PasswordResetModel {
	return &PasswordResetModel{
		db:                  m.db,
		tableName:           m.tableName,
		excludeGlobalScopes: append([]string{}, m.excludeGlobalScopes...),
		includeLocalScopes:  append([]string{}, m.includeLocalScopes...),
		query:               m.query,
	}
}

// WithoutGlobalScopes remove a global scope for given query
func (m *PasswordResetModel) WithoutGlobalScopes(names ...string) *PasswordResetModel {
	mc := m.clone()
	mc.excludeGlobalScopes = append(mc.excludeGlobalScopes, names...)

	return mc
}

// WithLocalScopes add a local scope for given query
func (m *PasswordResetModel) WithLocalScopes(names ...string) *PasswordResetModel {
	mc := m.clone()
	mc.includeLocalScopes = append(mc.includeLocalScopes, names...)

	return mc
}

// Query add query builder to model
func (m *PasswordResetModel) Query(builder query.SQLBuilder) *PasswordResetModel {
	mm := m.clone()
	mm.query = mm.query.Merge(builder)

	return mm
}

// Find retrieve a model by its primary key
func (m *PasswordResetModel) Find(id int64) (PasswordReset, error) {
	return m.First(m.query.Where("id", "=", id))
}

// Exists return whether the records exists for a given query
func (m *PasswordResetModel) Exists(builders ...query.SQLBuilder) (bool, error) {
	count, err := m.Count(builders...)
	return count > 0, err
}

// Count return model count for a given query
func (m *PasswordResetModel) Count(builders ...query.SQLBuilder) (int64, error) {
	sqlStr, params := m.query.
		Merge(builders...).
		Table(m.tableName).
		AppendCondition(m.applyScope()).
		ResolveCount()

	rows, err := m.db.QueryContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	defer rows.Close()

	rows.Next()
	var res int64
	if err := rows.Scan(&res); err != nil {
		return 0, err
	}

	return res, nil
}

func (m *PasswordResetModel) Paginate(page int64, perPage int64, builders ...query.SQLBuilder) ([]PasswordReset, query.PaginateMeta, error) {
	if page <= 0 {
		page = 1
	}

	if perPage <= 0 {
		perPage = 15
	}

	meta := query.PaginateMeta{
		PerPage: perPage,
		Page:    page,
	}

	count, err := m.Count(builders...)
	if err != nil {
		return nil, meta, err
	}

	meta.Total = count
	meta.LastPage = count / perPage
	if count%perPage != 0 {
		meta.LastPage += 1
	}

	res, err := m.Get(append([]query.SQLBuilder{query.Builder().Limit(perPage).Offset((page - 1) * perPage)}, builders...)...)
	if err != nil {
		return res, meta, err
	}

	return res, meta, nil
}

// Get retrieve all results for given query
func (m *PasswordResetModel) Get(builders ...query.SQLBuilder) ([]PasswordReset, error) {
	b := m.query.Merge(builders...).Table(m.tableName).AppendCondition(m.applyScope())
	if len(b.GetFields()) == 0 {
		b = b.Select(
			"email",
			"token",
			"id",
			"created_at",
		)
	}

	fields := b.GetFields()
	selectFields := make([]query.Expr, 0)

	for _, f := range fields {
		switch strcase.ToSnake(f.Value) {

		case "email":
			selectFields = append(selectFields, f)
		case "token":
			selectFields = append(selectFields, f)
		case "id":
			selectFields = append(selectFields, f)
		case "created_at":
			selectFields = append(selectFields, f)
		}
	}

	var createScanVar = func(fields []query.Expr) (*passwordResetWrap, []interface{}) {
		var passwordResetVar passwordResetWrap
		scanFields := make([]interface{}, 0)

		for _, f := range fields {
			switch strcase.ToSnake(f.Value) {

			case "email":
				scanFields = append(scanFields, &passwordResetVar.Email)
			case "token":
				scanFields = append(scanFields, &passwordResetVar.Token)
			case "id":
				scanFields = append(scanFields, &passwordResetVar.Id)
			case "created_at":
				scanFields = append(scanFields, &passwordResetVar.CreatedAt)
			}
		}

		return &passwordResetVar, scanFields
	}

	sqlStr, params := b.Fields(selectFields...).ResolveQuery()

	rows, err := m.db.QueryContext(context.Background(), sqlStr, params...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	passwordResets := make([]PasswordReset, 0)
	for rows.Next() {
		passwordResetVar, scanFields := createScanVar(fields)
		if err := rows.Scan(scanFields...); err != nil {
			return nil, err
		}

		passwordResetReal := passwordResetVar.ToPasswordReset()
		passwordResetReal.SetModel(m)
		passwordResets = append(passwordResets, passwordResetReal)
	}

	return passwordResets, nil
}

// First return first result for given query
func (m *PasswordResetModel) First(builders ...query.SQLBuilder) (PasswordReset, error) {
	res, err := m.Get(append(builders, query.Builder().Limit(1))...)
	if err != nil {
		return PasswordReset{}, err
	}

	if len(res) == 0 {
		return PasswordReset{}, query.ErrNoResult
	}

	return res[0], nil
}

// Create save a new PasswordReset to database
func (m *PasswordResetModel) Create(kv query.KV) (int64, error) {

	if _, ok := kv["created_at"]; !ok {
		kv["created_at"] = time.Now()
	}

	sqlStr, params := m.query.Table(m.tableName).ResolveInsert(kv)

	res, err := m.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.LastInsertId()
}

// SaveAll save all PasswordResets to database
func (m *PasswordResetModel) SaveAll(passwordResets []PasswordReset) ([]int64, error) {
	ids := make([]int64, 0)
	for _, passwordReset := range passwordResets {
		id, err := m.Save(passwordReset)
		if err != nil {
			return ids, err
		}

		ids = append(ids, id)
	}

	return ids, nil
}

// Save save a PasswordReset to database
func (m *PasswordResetModel) Save(passwordReset PasswordReset) (int64, error) {
	return m.Create(passwordReset.StaledKV())
}

// SaveOrUpdate save a new PasswordReset or update it when it has a id > 0
func (m *PasswordResetModel) SaveOrUpdate(passwordReset PasswordReset) (id int64, updated bool, err error) {
	if passwordReset.Id > 0 {
		_, _err := m.UpdateById(passwordReset.Id, passwordReset)
		return passwordReset.Id, true, _err
	}

	_id, _err := m.Save(passwordReset)
	return _id, false, _err
}

// UpdateFields update kv for a given query
func (m *PasswordResetModel) UpdateFields(kv query.KV, builders ...query.SQLBuilder) (int64, error) {
	if len(kv) == 0 {
		return 0, nil
	}

	sqlStr, params := m.query.Merge(builders...).AppendCondition(m.applyScope()).
		Table(m.tableName).
		ResolveUpdate(kv)

	res, err := m.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()
}

// Update update a model for given query
func (m *PasswordResetModel) Update(passwordReset PasswordReset) (int64, error) {
	return m.UpdateFields(passwordReset.StaledKV())
}

// UpdateById update a model by id
func (m *PasswordResetModel) UpdateById(id int64, passwordReset PasswordReset) (int64, error) {
	return m.Query(query.Builder().Where("id", "=", id)).Update(passwordReset)
}

// Delete remove a model
func (m *PasswordResetModel) Delete(builders ...query.SQLBuilder) (int64, error) {

	sqlStr, params := m.query.Merge(builders...).AppendCondition(m.applyScope()).Table(m.tableName).ResolveDelete()

	res, err := m.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()

}

// DeleteById remove a model by id
func (m *PasswordResetModel) DeleteById(id int64) (int64, error) {
	return m.Query(query.Builder().Where("id", "=", id)).Delete()
}
