package template

import (
	"fmt"
)

var temp = `
package {{ .PackageName }} 

// !!! DO NOT EDIT THIS FILE

import (
	{{ range $i, $imp := packages }}
	"{{ $imp }}"{{ end }}
)

func init() {
{{ range $i, $m := .Models }}{{ if $m.Definition.SoftDelete }}
	// Add{{camel $m.Name }}GlobalScope assign a global scope to a model for soft delete
	AddGlobalScopeFor{{ camel $m.Name }}("soft_delete", func(builder query.Condition) {
		builder.WhereNull("deleted_at")
	})
{{ end }}{{ end }}
}

{{ range $i, $m := .Models }}
%s
%s
%s
%s
%s
{{ end }}
`

func GetTemplate() string {
	return fmt.Sprintf(
		temp,
		GetEntityTemplate(),
		GetRelationTemplate(),
		GetScopeTemplate(),
		GetEntityPlainTemplate(),
		GetModelTemplate(),
	)
}
